name: Digital Ocean
# Using this configuration we can deploy project using SSH & github on Digital Ocean VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install speedtest-cli
        run: sudo apt-get install speedtest-cli
      - name: Test Internet Speed
        run: speedtest
      - name: Check Node Version
        run: node -v
      # DOC: https://github.com/marketplace/actions/ssh-remote-commands
      - name: Executing remote SSH command
        uses: appleboy/ssh-action@master
        env:
          PULL_FROM_BRANCH: ${{ secrets.PULL_FROM_BRANCH }}
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            whoami
            cd /var/www/garivaradev
            ls -al
            git remote -v
            git branch
            git checkout $PULL_FROM_BRANCH
            git branch --show-current
            git pull origin $PULL_FROM_BRANCH
            node -v
