name: Digital Ocean

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  #Run the container in droplet
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        env:
          PULL_FROM_BRANCH: ${{ secrets.PULL_FROM_BRANCH }}
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/garivaradev
            ls -l
            git remote -v
            git branch
            git pull origin $PULL_FROM_BRANCH
